### ISSUE TITLE
Can I work on your documentation?

### ISSUE THREAD

**Issue by sunkanmii** [eskopp/lichesspy#25]
Hey! 👋🏾

I'm Sunkanmi and I'm a Technical Writer looking to contribute to API documentation on Github. I want to know if I can submit a PR for a Swagger documentation for this API and help refine your Github readme as well.

Let me know if I can get started on this. :)

Hope to speak with you soon!

**Comment by eskopp** [comment]
This is just a simple and repaired copy of the Gits [https://github.com/cyanfish/python-lichess](https://github.com/cyanfish/python-lichess). Nothing more is being developed here. I check every now and then to see if the tool is still working. But not much will happen here.

If you want to help the Lichess API, have a look at much better projects like [https://github.com/lichess-org/berserk](https://github.com/lichess-org/berserk)
